# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  notification:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION:-latest}
    restart: unless-stopped
    secrets:
      - osia-jwt
      - osia-mgnt-url
      - in-groupe-mgnt-url
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - CONFIG_HOST=http://config:2021
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - OPENHIM_URL=http://openhim-core:5001/fhir
      - CONFIRM_REGISTRATION_URL=http://openhim-core:5001/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - HOSTNAME=${HOSTNAME}
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
      - OSIA_UIN_MANAGEMENT_URL_PATH=/run/secrets/osia-mgnt-url
      - INGROUPE_UIN_MANAGEMENT_URL_PATH=/run/secrets/in-groupe-mgnt-url
      - OSIA_JWT_PATH=/run/secrets/osia-jwt

    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT = 100

  gateway:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
      - NATIONAL_ID_OIDP_BASE_URL=https://idp-mock.collab.mosip.net/
      - NATIONAL_ID_OIDP_CLIENT_PRIVATE_KEY=ewogICAgInAiOiAiNC13dWRnbUVQOC1aSWhfSnpGQlg5akptQmI3YW1NNWVPbUUxdUtuN0JScjZkblVhWHlJcjl4M2MxZm1ENUQ5QnJ2WVJzR0d0UC1ramotZXNKeFdkQ1ppYm1vWmctVFp0bnZ0MnRqNTh4eHNwMnFJMUprUEs1S1hpNm5DZnoyTGtSRGtxajVocTNlQXZlZDZpZUJUbmktcGhqV240MjEtazFzalBNWmJRT19jIiwKICAgICJrdHkiOiAiUlNBIiwKICAgICJxIjogInJrWkRYRjNwVW04Y0ZmM2dENmtsRVFfS1BYQi1kdVNyUUp1WlA2aVQxcnEwZ3Y2b2RxUUt4cEVXNmU1Qjd3NnkwU3pVRGFCZVhyRmZMcXlGT1ZGZEhGaVp5ODBmMFhOTzhHNkZqNjh1dXNqc0w1aHdSbmRxLTNHRHFCTTZOWXBfRjVFU2tvVXJPcVEzbDB5QmdXZTZMeWdTRnVwMTV6VU5VZHpscGxyVnU5YyIsCiAgICAiZCI6ICJJNi1LY0p4aUlvcldxR0lEVjBocTl0ZHljTTFxS2pPbDBERlhjUlhOdDZVUW9QbkdqUDk1cVFsQTg4M1FLQzZhWHRyRnZ0YS1UMUs2dkhjdnZ5QXhFR1hTckJvWVlXYnBVbzlEOFN0YV9sd3V6Wm5Yb1V0YjdKTUtGNjRGV1lkS2lmV1NWZEdvdEhrX0tZdFJaazNLd0FCR0ptSGJlNkR5TlROLVJudlcyQ3pidEt1bUtzSWpaUHpZUk4zNzdLQ2JiYzR4N1MwY2dNb25VdVk5Rm9pZXRwUWVzYXVGcmNrTmhhVktYa190N1Buc3k4dEhCbEtWeFVVYkU4TGR0LWZrbVFXNmYxUnZiM3RkNHNkRERaRjc4RHZWMFlHd0Z0S0pLODJnRlZEWTZaM0hvTTFKaGJyRk56YWpDTUpwd0c4TGtDcWJmUXlfUlhXLWhsN241eDVwSlEiLAogICAgImUiOiAiQVFBQiIsCiAgICAicWkiOiAiMGJNS1BfTFFHUWkxZ3RVNjIwb1R5RjR5dGY3QXBmU1dCN1BtSHJfT3JCU3F1Q0s3T1hiUW40enBpUXdkb2tvc3RWS0thT0tYblQ0aldVejNCQllBaDBDSmNibnphMTdMVXdKMWQ3QW1Bdnp3LVdQa3hMZWJDMWZta013SlFoOTN5YmdOMnphYXlxdTBNd0s3a1VDTm9XcHo1TUNUZ210Q2JDbWFfOEZGODc0IiwKICAgICJkcCI6ICJVQU5XNEN0QkdTR284WmpWUF91b2xZNWwwSGlLeHdBVGhrMGdEZDdtZDRsY0NmX2NMUy1TM2FMSEp2cjhPVUdYcm5OR0RIU04zSlRjM2lVSGc0VUw1eFdDOHNGZ0E3ei15TVFnamFQc0tfMjJPTUdmQlByaG5GazhDdTlVdXZwTmhrSEhWamU4dEgyQ1RUZENOQU9xc2F5cmFIaWVXMno5TWtXMnJ3THh3VXMiLAogICAgImRxIjogImNGMFBLMnZGZHdmNmxOZFdjdUo4NnE1Q21EQ0M2WWR3UHp6VHB5NjYtMVR2OUJIYmJudEFFMTBTNkF0ZGFaUVJpVHFkRXBnV29Iay1SR3FwanhZOXNYd1MxVXRSTzR0Y0Z6czdWRFFBTGlCRDRFQXFDOVVOSGtmSE9rUURZT2dHSDV6QzI4T081c1Zncm1WLWpuX2hsR3dDbGRIZjZRM1VvN2FJUHlVTDc0cyIsCiAgICAibiI6ICJteWtXSWZ0a25LMVRRbWJpYXp1aWswcldHc3hlT0lVRTN5ZlNRSmdvQ2ZkR1hZNEhmSEU2QWxOS0ZkSUtaT1hlLVUtTDIxS2xqNjkyZTlpWngwNXJISGFadk8wYTRJenlGTU95dzV3akJDV29CT2NBNHE5M0xQa1pUU2tJcTlJMlZncjZCend1Nlg3UVBNYm1GOHhBS1g0S2VTbl95WmNzQWhFbEhCT1drRU5tS3A3NnlDeVRlRTREQUlHYWgxQmNnaUJfS1d2T1pPZWR3VFJETHlRMERaTTF6MDctTi1yUGgwcVNkMlVGUlJZLWJfamM5b3BqeVJRcTNkNVpraUI5VzRSZUFVaElLQTl1YzFSRHMxc2hjM0c4emdacDNxSDZmWVdtc09pMjNCT0FfcThaLXdNSHdQSzJ2RUp2Z1pJV292QUc1akdGYk1pbE5jRlFmekxKY1EiCn0=

  workflow:
    environment:
      - LANGUAGES=en,fr
      - MOSIP_TOKEN_SEEDER_URL=http://mosiptokenseeder:8080
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  auth:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  user-mgnt:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
      - NATIONAL_ID_OIDP_BASE_URL=https://idp-mock.collab.mosip.net/
      - NATIONAL_ID_OIDP_CLIENT_ID=3yz7-j3xRzU3SODdoNgSGvO_cD8UijH3AIWRDAg1x-M
      - NATIONAL_ID_OIDP_ESSENTIAL_CLAIMS=name,address,phone_number,email,gender,birthdate
  
  config:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  metrics:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  search:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  webhooks:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
  
  # webhook-mediator:
  #  image: opencrvs/webhook-mediator:91aca1e
  #  build:
  #    context: .
  #    dockerfile: ./packages/api/Dockerfile
  #  restart: unless-stopped
  #  environment:
  #    - NODE_ENV=development
  #    - WEBHOOK_URL=http://webhook-mediator:4545/webhooks
  #    - AUTH_URL=http://auth:4040
  #    - CALLBACK_URL=http://webhook-mediator:4545/webhooks
  #    - SHA_SECRET_PATH=/run/secrets/sha-secret
  #    - CLIENT_SECRET_PATH=/run/secrets/client-secret
  #    - CLIENT_ID_PATH=/run/secrets/client-id
  #  secrets:
  #    - jwt-public-key.{{ts}}
  #    - sha-secret
  #    - client-secret
  #    - client-id
  #  deploy:
  #    labels:
  #      - 'traefik.enable=true'
  #      - 'traefik.http.routers.webhook-mediator.rule=Host(`webhook-mediator.farajaland-demo.opencrvs.org`)'
  #      - 'traefik.http.services.webhook-mediator.loadbalancer.server.port=4040'
  #      - 'traefik.http.routers.webhook-mediator.tls=true'
  #      - 'traefik.http.routers.webhook-mediator.tls.certresolver=certResolver'
  #      - 'traefik.http.routers.webhook-mediator.entrypoints=web,websecure'
  #      - 'traefik.docker.network=opencrvs_overlay_net'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.customresponseheaders.Pragma=no-cache'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.customresponseheaders.Cache-control=no-store'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.customresponseheaders.X-Robots-Tag=none'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.stsseconds=31536000'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.stsincludesubdomains=true'
  #      - 'traefik.http.middlewares.webhook-mediator.headers.stspreload=true'
  #    replicas: 1
  #  networks:
  #    - overlay_net
  #  logging:
  #    driver: gelf
  #    options:
  #      gelf-address: 'udp://127.0.0.1:12201'
  #      tag: 'webhook-mediator'

secrets:
  osia-jwt:
    external: true
  osia-mgnt-url:
    external: true
  in-groupe-mgnt-url:
    external: true
  openhim-user:
    external: true
  openhim-password:
    external: true
  sha-secret:
    external: true
  client-secret:
    external: true
  client-id:
    external: true
