name: Restore a QA or Production backup on QA
run-name: Restore a ${{ github.event.inputs.testing-prod-backup }} backup on QA
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to run workflow from
        default: develop
        required: true
      qa-backup-label:
        description: Your lowercase QA backup label
        required: true
      prod-backup-label:
        description: Your lowercase prod backup label
      testing-prod-backup:
        type: choice
        description: Whether to restore a qa or production backup
        required: true
        default: 'no'
        options:
          - 'qa'
          - 'production'
jobs:
  restore-backup:
    environment: qa
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: '${{ github.event.inputs.branch_name }}'
      
      #
      # Uncomment if using VPN
      #
      #- name: Install openconnect ppa
      #  run: sudo add-apt-repository ppa:dwmw2/openconnect -y && sudo apt update
      
      #- name: Install openconnect
      #  run: sudo apt install -y openconnect
      
      #- name: Connect to VPN
      #  run: |
      #    echo "${{ secrets.VPN_PWD }}" | sudo openconnect -u ${{ secrets.VPN_USER }} --passwd-on-stdin --protocol=${{ secrets.VPN_PROTOCOL }} ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --servercert ${{ secrets.VPN_SERVERCERT }} --background

      #- name: Test if IP is reachable
      #  run: |
      #    ping -c4 ${{ secrets.SSH_HOST }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Test a production backup on QA
        id: production-backup-check
        if: ${{ github.event.inputs.testing-prod-backup == 'production' }}
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          BACKUP_HOST: ${{ secrets.BACKUP_HOST }}
          BACKUP_DIRECTORY: ${{ vars.BACKUP_DIRECTORY }}
          RESTORE_DIRECTORY: ${{ vars.RESTORE_DIRECTORY }}
          REPLICAS: ${{ vars.REPLICAS }}
          QA_BACKUP_LABEL: ${{ github.event.inputs.qa-backup-label }}
          PROD_BACKUP_LABEL: ${{ github.event.inputs.prod-backup-label }}
          REVERTING: "no"
        run: |
          bash infrastructure/test-restore-backup.sh

      - name: Restore a QA backup
        id: qa-backup-check
        if: ${{ github.event.inputs.testing-prod-backup == 'qa' }}
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          BACKUP_HOST: ${{ secrets.BACKUP_HOST }}
          BACKUP_DIRECTORY: ${{ vars.BACKUP_DIRECTORY }}
          RESTORE_DIRECTORY: ${{ vars.RESTORE_DIRECTORY }}
          REPLICAS: ${{ vars.REPLICAS }}
          QA_BACKUP_LABEL: ${{ github.event.inputs.qa-backup-label }}
          PROD_BACKUP_LABEL: ""
          REVERTING: "yes"
        run: |
          bash infrastructure/test-restore-backup.sh